export const SupportedLanguages = [
    { name: "Afrikaans", type: "af", code: "af-ZA" },
    { name: "Albanian", type: "sq", code: "sq" },
    { name: "Amharic", type: "am", code: "am" },
    { name: "Arabic", type: "ar", code: "ar-SA" },
    { name: "Armenian", type: "hy", code: "hy" },
    { name: "Assamese", type: "as", code: "as" },
    { name: "Aymara", type: "ay", code: "ay" },
    { name: "Azerbaijani", type: "az", code: "az" },
    { name: "Bambara", type: "bm", code: "bm" },
    { name: "Basque", type: "eu", code: "eu" },
    { name: "Belarusian", type: "be", code: "be" },
    { name: "Bengali", type: "bn", code: "bn-IN" },
    { name: "Bhojpuri", type: "bho", code: "bho" },
    { name: "Bosnian", type: "bs", code: "bs" },
    { name: "Bulgarian", type: "bg", code: "bg" },
    { name: "Catalan", type: "ca", code: "ca-ES" },
    { name: "Cebuano", type: "ceb", code: "ceb" },
    { name: "Chichewa", type: "ny", code: "ny" },
    { name: "Chinese (Simplified)", type: "zh-CN", code: "zh-CN" },
    { name: "Chinese (Traditional)", type: "zh-TW", code: "zh-TW" },
    { name: "Corsican", type: "co", code: "co" },
    { name: "Croatian", type: "hr", code: "hr" },
    { name: "Czech", type: "cs", code: "cs-CZ" },
    { name: "Danish", type: "da", code: "da-DK" },
    { name: "Dhivehi", type: "dv", code: "dv" },
    { name: "Dogri", type: "doi", code: "doi" },
    { name: "Dutch", type: "nl", code: "nl-NL" },
    { name: "English", type: "en", code: "en-US" },
    { name: "Esperanto", type: "eo", code: "eo" },
    { name: "Estonian", type: "et", code: "et-EE" },
    { name: "Ewe", type: "ee", code: "ee" },
    { name: "Filipino", type: "fil", code: "fil-PH" },
    { name: "Finnish", type: "fi", code: "fi-FI" },
    { name: "French", type: "fr", code: "fr-FR" },
    { name: "Frisian", type: "fy", code: "fy" },
    { name: "Galician", type: "gl", code: "gl" },
    { name: "Georgian", type: "ka", code: "ka" },
    { name: "German", type: "de", code: "de-DE" },
    { name: "Greek", type: "el", code: "el-GR" },
    { name: "Guarani", type: "gn", code: "gn" },
    { name: "Gujarati", type: "gu", code: "gu-IN" },
    { name: "Haitian Creole", type: "ht", code: "ht" },
    { name: "Hausa", type: "ha", code: "ha" },
    { name: "Hawaiian", type: "haw", code: "haw" },
    { name: "Hebrew", type: "he", code: "he-IL" },
    { name: "Hindi", type: "hi", code: "hi-IN" },
    { name: "Hmong", type: "hmn", code: "hmn" },
    { name: "Hungarian", type: "hu", code: "hu-HU" },
    { name: "Icelandic", type: "is", code: "is-IS" },
    { name: "Igbo", type: "ig", code: "ig" },
    { name: "Indonesian", type: "id", code: "id-ID" },
    { name: "Irish", type: "ga", code: "ga" },
    { name: "Italian", type: "it", code: "it-IT" },
    { name: "Japanese", type: "ja", code: "ja-JP" },
    { name: "Javanese", type: "jv", code: "jv" },
    { name: "Kannada", type: "kn", code: "kn-IN" },
    { name: "Kazakh", type: "kk", code: "kk" },
    { name: "Khmer", type: "km", code: "km" },
    { name: "Kinyarwanda", type: "rw", code: "rw" },
    { name: "Korean", type: "ko", code: "ko-KR" },
    { name: "Kurdish (Kurmanji)", type: "ku", code: "ku" },
    { name: "Kurdish (Sorani)", type: "ckb", code: "ckb" },
    { name: "Kyrgyz", type: "ky", code: "ky" },
    { name: "Lao", type: "lo", code: "lo" },
    { name: "Latin", type: "la", code: "la" },
    { name: "Latvian", type: "lv", code: "lv-LV" },
    { name: "Lingala", type: "ln", code: "ln" },
    { name: "Lithuanian", type: "lt", code: "lt-LT" },
    { name: "Luxembourgish", type: "lb", code: "lb" },
    { name: "Macedonian", type: "mk", code: "mk" },
    { name: "Malay", type: "ms", code: "ms-MY" },
    { name: "Malayalam", type: "ml", code: "ml-IN" },
    { name: "Maltese", type: "mt", code: "mt" },
    { name: "Maori", type: "mi", code: "mi" },
    { name: "Marathi", type: "mr", code: "mr-IN" },
    { name: "Mongolian", type: "mn", code: "mn" },
    { name: "Myanmar (Burmese)", type: "my", code: "my" },
    { name: "Nepali", type: "ne", code: "ne-NP" },
    { name: "Norwegian", type: "no", code: "no-NO" },
    { name: "Pashto", type: "ps", code: "ps" },
    { name: "Persian", type: "fa", code: "fa-IR" },
    { name: "Polish", type: "pl", code: "pl-PL" },
    { name: "Portuguese", type: "pt", code: "pt-PT" },
    { name: "Punjabi", type: "pa", code: "pa-IN" },
    { name: "Romanian", type: "ro", code: "ro-RO" },
    { name: "Russian", type: "ru", code: "ru-RU" },
    { name: "Samoan", type: "sm", code: "sm" },
    { name: "Serbian", type: "sr", code: "sr" },
    { name: "Sinhala", type: "si", code: "si-LK" },
    { name: "Slovak", type: "sk", code: "sk-SK" },
    { name: "Slovenian", type: "sl", code: "sl-SI" },
    { name: "Somali", type: "so", code: "so" },
    { name: "Spanish", type: "es", code: "es-ES" },
    { name: "Sundanese", type: "su", code: "su" },
    { name: "Swahili", type: "sw", code: "sw" },
    { name: "Swedish", type: "sv", code: "sv-SE" },
    { name: "Tajik", type: "tg", code: "tg" },
    { name: "Tamil", type: "ta", code: "ta-IN" },
    { name: "Tatar", type: "tt", code: "tt" },
    { name: "Telugu", type: "te", code: "te-IN" },
    { name: "Thai", type: "th", code: "th-TH" },
    { name: "Turkish", type: "tr", code: "tr-TR" },
    { name: "Ukrainian", type: "uk", code: "uk-UA" },
    { name: "Urdu", type: "ur", code: "ur-PK" },
    { name: "Uzbek", type: "uz", code: "uz" },
    { name: "Vietnamese", type: "vi", code: "vi-VN" },
    { name: "Welsh", type: "cy", code: "cy" },
    { name: "Xhosa", type: "xh", code: "xh" },
    { name: "Yiddish", type: "yi", code: "yi" },
    { name: "Yoruba", type: "yo", code: "yo" },
    { name: "Zulu", type: "zu", code: "zu" }
];


export const RightSideStartedLanguages = ["ar", "he", "ps", "fa", "ur"]